INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (2, 'The wind ', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', '2022-01-27 23:46:17.860000 +00:00', null, 1);
INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (4, 'This title is long like the river.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', '2022-01-27 23:47:11.626000 +00:00', null, 1);
INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (5, 'This title is long like the river.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', '2022-01-27 23:47:11.626000 +00:00', null, 1);
INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (6, 'The wind ', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', now(), null, 1);
INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (7, 'This title is long like the river.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', now(), null, 1);
INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (8, 'This title is long like the river.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', now(), null, 1);
INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (9, 'The wind ', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', '2022-01-27 23:46:17.860000 +00:00', null, 1);
INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (10, 'This title is long like the river.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', '2022-01-27 23:47:11.626000 +00:00', null, 1);
INSERT INTO public.article (id, title, body, created_date, updated_date, user_id) VALUES (11, 'This title is long like the river.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap', '2022-01-27 23:47:11.626000 +00:00', null, 1);
